### PR TITLE
Repaired WJoy with the original driver code

### PR DESCRIPTION
**Pull request by doctorpangloss**
Posting this to aid in discovery.  I am awaiting a KEXT signing cert, but otherwise this works with SIP disabled.

### CODE REVIEW

**Comment by franciscolourenco** [comment]
looking forward for the KEXT signing cert

**Comment by franciscolourenco** [comment]
you might want to enable issues on hiddenswitch/wjoy

**Comment by doctorpangloss** [comment]
Done 

-Ben

**Comment by JustinBis** [comment]
Thanks for the PR! Would love to see this get signed with a KEXT cert.

**Pull request merged**
